version: 0.2

env:
  variables:
    IMAGE_TAG: generate-products-v1
    ECR_REPO: lakehouse-lambdas

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPO_URI:$IMAGE_TAG .
      - echo Pushing to ECR...
      - docker push $REPO_URI:$IMAGE_TAG

artifacts:
  files: '**/*'
