version: 0.2

env:
  variables:
    IMAGE_TAG: create-products-latest
    ECR_REPO: lakehouse-lambdas

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AWS_REGION=$(aws configure get region)
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO
      - echo Using REPO_URI=$REPO_URI
      - docker login -u AWS -p "$(aws ecr get-login-password --region $AWS_REGION)" $REPO_URI

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPO_URI:$IMAGE_TAG .
      - echo Pushing to ECR...
      - docker push $REPO_URI:$IMAGE_TAG

artifacts:
  files: '**/*'
